### ISSUE TITLE
Sign the assemblies.

### ISSUE THREAD

**Issue by hazzik** [FireflyServer/firefly#7]

**Comment by loudej** [comment]
Can be done. What's the reason you would like them signed? I ask because people can have different opinions about signed/unsigned and I'm curious what factors weigh into that.

**Comment by hazzik** [comment]
I want to use it in another OSS project and this project is signed.

**Comment by loudej** [comment]
Try getting the latest http://nuget.org/packages/firefly - firefly.dll and owin.dll should be signed now
